version: 1.0.{build}
image:
- Visual Studio 2015
- Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
matrix:
    fast_finish: true
init:
- cmd: >-
    echo %APPVEYOR_BUILD_WORKER_IMAGE%

    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017 Win64" )

    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015 Win64" )

    echo %generator%
before_build:
- cmd: >-
    mkdir build

    cd build

    cmake --version

    cmake .. -G %generator%

test_script:
- ps: >-
    ..\test.ps1
